site_name: Retirement Income Toolkit
theme:
  name: material
  palette:
    scheme: deep purple
  features:
    - navigation.tabs
    - content.code.annotate
repo_url: https://github.com/print-hi/retirement-toolkit


# =============================================================================
# pages:
#   - Home: 'index.md'
# =============================================================================
nav:
  - Home: 'index.md'
  - Overview:
    - 'Getting Started': 'Home/start.md'
    - 'About': 'Home/about.md'
    - 'Changelog': 'Home/log.md'
  - Aggregate Mortality:
    - 'Aggregate Mortality/overview.md'
    - 'Aggregate Mortality/rate_change.md'
    - 'Aggregate Mortality/rate_completion.md'
    - 'Aggregate Mortality/period_cohort.md'
    - 'Aggregate Mortality/rate_survival.md'
    - 'Aggregate Mortality/risk_neutral.md'
    - 'Aggregate Mortality/simulation.md'
    - 'Aggregate Mortality/stats_functions.md'
  - Health State:
    - 'Health/overview.md'
    - Multi-State Model:
      - 'Health/Multi State Model/3_state_model.md'
      - 'Health/Multi State Model/5_state_model.md'
    - Cox Hazard Regression:
      - 'Health/Cox Hazard Regression/cox_model_3.md'
      - 'Health/Cox Hazard Regression/cox_model_5.md'
    - 'Health/trans_probs.md'
    - 'Health/lifetable.md'
    - 'Health/simulation.md'
    - Statistics:
      - 'Health/Statistics/stats_3.md'
      - 'Health/Statistics/stats_5.md'
    - 'Health/workflow.md'
  - Economic Scenario Generator:
    - 'Economic Scenario Generator/overview.md'
    - 'Economic Scenario Generator/discrete_esg.md'
    - 'Economic Scenario Generator/cts_esg.md'
    - 'Economic Scenario Generator/summary_esg.md'
  - Policy Valuation:
    - 'Policy Valuation/overview.md'
    - 'Policy Valuation/policy.md'
    - 'Policy Valuation/cashflow.md'
    - 'Policy Valuation/pricing.md'
    - 'Policy Valuation/workflow.md'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences  
  - pymdownx.arithmatex:
      generic: true
  - codehilite
  - pymdownx.details
  - admonition
  - attr_list
  - md_in_html
      
# for pymdown.arithmatex 
extra_javascript:
  - 'expand.js'
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
